Add a new event type for subscriptions migrated to a bundle
RocketChat/marketplace-go pull request #5
Opened 2022-07-05 10:05 UTC by matheuslc

# What? :boat:

We are introducing a new event type called `app.subscription.bundle.migrated` that happens when an app subscription is migrated to a bundle. We are also introducing a new field called MigratedToBundle that holds the information if the actual subscription was either migrated or not.

# Why? :thinking:

# Checklist :ballot_box_with_check:
- [ ] **I have added added tests for PR or I have justified why this PR doesn't need tests.**
- [ ] **Swager definition added (if new route or route is adjusted)**

# Links :earth_americas:
[Task](https://app.clickup.com/t/2hz8f3h)

# PS :video_game:

2022-07-05 13:51 UTC, graywolf336 requested changes

2022-07-05 13:51 UTC, graywolf336 commented on events/event.go
> +	CurrentAPIVersion APIVersion = "0.1.0"
```suggestion
	CurrentAPIVersion APIVersion = "1.1.0"
```
We don't need to go back in versions. I know that we are the ones primarily consuming this, but I would prefer us to just move forward.

2022-07-05 14:07 UTC, matheuslc commented on events/event.go
> +	CurrentAPIVersion APIVersion = "0.1.0"
@graywolf336 My intent was to start using the version (tag) we generate for each new release. So, I moved from 0.0.3 to 0.1.0.

But what do you think? 🤔 We could keep them separated if you want

2022-07-05 16:07 UTC, graywolf336 commented on events/event.go
> +	CurrentAPIVersion APIVersion = "0.1.0"
I think we move forward with the code. I need to bump the version tags.

2022-07-07 15:21 UTC, graywolf336 requested changes

2022-07-07 15:21 UTC, graywolf336 commented on events/types.go
> +	AppBundleSubscriptionMigratedEventType EventType = "app.subscription.bundle.migrated"
```suggestion
	AppBundleSubscriptionMigratedEventType EventType = "app.subscription.migrated"
```
Let's go with this as the name of the event. Also, if you can move this up underneath the group of events related to subscriptions that would be great.

I am thinking something like: `item.relatedItem.action` and if there's no related item it would be `item.action`

So this would be `app.x.created` and if there's no related item then it would be `app.created` or `app.updated` or `publisher.updated`. Then if we want more information about the event, it should be inside the event's data and detail.

For this event, it would be `app.subscription.migrated` and the detail data would be `MigratedToBundle` and if the subscription got migrated to a free version the `MigratedToFree` could be a flag.

Thoughts?

2022-07-07 16:17 UTC, matheuslc commented on events/types.go
> +	AppBundleSubscriptionMigratedEventType EventType = "app.subscription.bundle.migrated"
I really liked the proposed pattern. I also liked the suggestion to change the event name for `app.subscription.migrated` based on this rationale. It's also easier to guess the event subject. 

For instance, if we are now creating an event related to a bundle, we can do something like that `bundle.app.removed`?

2022-07-07 16:29 UTC, graywolf336 commented on events/types.go
> +	AppBundleSubscriptionMigratedEventType EventType = "app.subscription.bundle.migrated"
Yes sir, precisely. That tells me an app was removed from a bundle, which makes perfect sense.

2022-07-07 17:16 UTC, matheuslc commented on events/types.go
> +	AppBundleSubscriptionMigratedEventType EventType = "app.subscription.bundle.migrated"
Awesome! 🙌 changes submitted to the branch ✅

2022-07-07 19:05 UTC, graywolf336 approved these changes

2022-07-07 19:06 UTC, merged